// Generate `src/tables.wac` by asking the host what it knows about every code point.
//
// The host already carries a Unicode database — that is what `toLowerCase` consults — so the
// tables are *derived from the authority* rather than transcribed from it. The same move as
// `packages/codec`, where RFC 4648's own vectors are the oracle: take the data from the thing
// that defines it, then check the result against that same thing from the other direction.
//
// Only simple, single-code-point mappings are emitted. Where the host maps one code point to
// several — `ß` uppercases to `SS`, `ﬁ` to `FI` — the entry is omitted and the code point maps to
// itself. That is the difference between *simple* and *full* case mapping, and the tests assert
// exactly where the boundary falls rather than skipping those code points.
//
//   deno run -A packages/unicode/tools/gentables.ts

const MAX = 0x10ffff;

type Pair = { from: number; to: number };

const lower: Pair[] = [];
const upper: Pair[] = [];
const fold: Pair[] = [];

/** The single code point `s` maps to, or -1 if it is not exactly one. */
function single(s: string): number {
  const points = [...s];
  return points.length === 1 ? points[0].codePointAt(0)! : -1;
}

for (let cp = 0; cp <= MAX; cp++) {
  // Surrogates are not scalar values and `fromCodePoint` will not make one.
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  const ch = String.fromCodePoint(cp);

  const lo = single(ch.toLowerCase());
  if (lo >= 0 && lo !== cp) lower.push({ from: cp, to: lo });

  const up = single(ch.toUpperCase());
  if (up >= 0 && up !== cp) upper.push({ from: cp, to: up });

  // Simple case folding: two code points are case-insensitively equal exactly when they fold to
  // the same value. Derived as lower(upper(cp)) rather than lower(cp), because lowercase alone
  // does not unify a *contextual* form with its base — Greek final sigma `ς` lowercases to
  // itself, so `ΣΊΣΥΦΟΣ` and `σίσυφος` would not have compared equal. Going up first collapses
  // both sigmas to `Σ`, and coming back down gives `σ` for each.
  //
  // Where either direction is not a single code point the fold is the identity, which is what
  // *simple* folding means: `ß` folds to itself, and only full folding turns it into `ss`.
  const viaUpper = up >= 0 ? single(String.fromCodePoint(up).toLowerCase()) : -1;
  const folded = viaUpper >= 0 ? viaUpper : (lo >= 0 ? lo : cp);
  if (folded !== cp) fold.push({ from: cp, to: folded });
}

function emit(name: string, pairs: Pair[]): string {
  const froms = pairs.map(p => p.from).join(", ");
  const tos = pairs.map(p => p.to).join(", ");
  return `/** ${pairs.length} code points. Sorted, so a lookup is a binary search. */\n`
    + `const i32[] ${name}_KEYS = i32[](${froms});\n`
    + `const i32[] ${name}_VALUES = i32[](${tos});\n`;
}

const out = `// Generated by tools/gentables.ts. Do not edit.
//
// Three sorted tables of (code point, mapping) pairs, holding only the code points whose mapping
// differs from themselves — about ${lower.length + upper.length} entries rather than 1.1 million.
// A lookup is a binary search over KEYS and an index into VALUES.
//
// Simple mappings only: where the host maps one code point to several, there is no entry and the
// code point maps to itself. See the package README.

${emit("LOWER", lower)}
${emit("UPPER", upper)}
${emit("FOLD", fold)}
/** Binary search: the mapping for \`cp\`, or \`cp\` itself. */
i32 lookup(const i32[] keys, const i32[] values, i32 cp) {
  i32 lo = 0;
  i32 hi = keys.len() - 1;
  while (lo <= hi) {
    i32 mid = lo + (hi - lo) / 2;
    if (keys[mid] == cp) { return values[mid]; }
    if (keys[mid] < cp) { lo = mid + 1; } else { hi = mid - 1; }
  }
  return cp;
}

export i32 simpleLower(i32 cp) { return lookup(LOWER_KEYS, LOWER_VALUES, cp); }
export i32 simpleUpper(i32 cp) { return lookup(UPPER_KEYS, UPPER_VALUES, cp); }
export i32 simpleFold(i32 cp) { return lookup(FOLD_KEYS, FOLD_VALUES, cp); }
`;

await Deno.writeTextFile("packages/unicode/src/tables.wac", out);
console.log(`lower ${lower.length}, upper ${upper.length}, fold ${fold.length}`);
console.log(`wrote packages/unicode/src/tables.wac (${(out.length / 1024).toFixed(1)} KiB)`);
