import { wacBind } from "./harness/wacBind.ts";
const m = await wacBind("packages/tls/test/wac/probe.wac");
const raw = await Deno.readFile("/tmp/clienthello.bin");
const hs = raw.subarray(5);                       // strip the record header
const body = (m.tlsMessageBody as (x:Uint8Array)=>Uint8Array)(hs);
const flat = (m.tlsParseClientHello as (b:Uint8Array,p:number)=>Uint8Array)(body, 0x1301);
const dec = new TextDecoder();
let p = 0;
const suite = (flat[0]<<8)|flat[1]; p = 2;
const flags = flat[p]; p++;
const sidLen = flat[p]; p++; const sid = flat.subarray(p, p+sidLen); p += sidLen;
const ksLen = flat[p]; p++; const ks = flat.subarray(p, p+ksLen); p += ksLen;
const nameLen = (flat[p]<<8)|flat[p+1]; p += 2; const name = flat.subarray(p, p+nameLen); p += nameLen;
const random = flat.subarray(p, p+32);
const hex = (b: Uint8Array) => Array.from(b).map(x=>x.toString(16).padStart(2,"0")).join("");
console.log("suite:      0x" + suite.toString(16));
console.log("tls1.3:    ", (flags & 1) !== 0);
console.log("ed25519:   ", (flags & 2) !== 0);
console.log("sessionId: ", sidLen, "bytes");
console.log("keyShare:  ", ksLen, "bytes", hex(ks).slice(0,24) + "…");
console.log("serverName:", JSON.stringify(dec.decode(name)));
console.log("random:    ", hex(random).slice(0,24) + "…");
