// ML-KEM's refusals.
//
// Only the refusals. Byte-identical key generation from a seed, decapsulating WebCrypto's
// ciphertext, determinism in the randomness and implicit rejection all moved to
// `test/wac/mlkem_test.wac` — with the vectors generated by WebCrypto on the host and
// passed in as data, because WebCrypto is asynchronous and a wasm call cannot await it.
//
// These stayed because they trap. The coefficient range check is the one worth keeping
// sharp: FIPS 203 §7.2 requires that every twelve-bit coefficient be below q, and the
// check is that re-encoding what was decoded gives back the original bytes. Skipping it
// lets a peer choose arithmetic outside the ring — and it was skipped, until a
// deliberately malformed key found that byteDecode was not reducing at twelve bits.

import { wacBind } from "../../../harness/wacBind.ts";

const mod = await wacBind("packages/crypto/test/wac/mlkem_probe.wac");
const keyGen = mod.kemKeyGen as (seed: Uint8Array) => Uint8Array;
const encaps = mod.kemEncaps as (ek: Uint8Array, m: Uint8Array) => Uint8Array;
const decaps = mod.kemDecaps as (dk: Uint8Array, ct: Uint8Array) => Uint8Array;

const hex = (b: Uint8Array) => Array.from(b).map(x => x.toString(16).padStart(2, "0")).join("");
const traps = (f: () => unknown) => { try { f(); return false; } catch { return true; } };

const EK_LEN = 1184, DK_LEN = 2400, CT_LEN = 1088;

/** WebCrypto's ML-KEM-768, with the non-standard-typed methods narrowed. */
const subtle = crypto.subtle as unknown as {
  encapsulateBits(a: unknown, k: CryptoKey): Promise<{ ciphertext: ArrayBuffer; sharedKey: ArrayBuffer }>;
  decapsulateBits(a: unknown, k: CryptoKey, c: BufferSource): Promise<ArrayBuffer>;
};

async function webcryptoKey() {
  const kp = await crypto.subtle.generateKey(
    { name: "ML-KEM-768" } as AlgorithmIdentifier, true,
    ["encapsulateBits", "decapsulateBits"] as unknown as KeyUsage[]) as CryptoKeyPair;
  return {
    kp,
    seed: new Uint8Array(await crypto.subtle.exportKey("raw-seed" as "raw", kp.privateKey)),
    ek: new Uint8Array(await crypto.subtle.exportKey("raw-public" as "raw", kp.publicKey)),
  };
}

Deno.test("mlkem: rejects malformed keys and ciphertexts", () => {
  const seed = new Uint8Array(64);
  const both = keyGen(seed);
  const ek = both.subarray(0, EK_LEN);
  const dk = both.subarray(EK_LEN);
  const m = new Uint8Array(32);

  for (const n of [0, 63, 65]) {
    if (!traps(() => keyGen(new Uint8Array(n)))) throw new Error(`accepted a ${n}-byte seed`);
  }
  for (const n of [0, EK_LEN - 1, EK_LEN + 1]) {
    if (!traps(() => encaps(new Uint8Array(n), m))) throw new Error(`accepted a ${n}-byte encapsulation key`);
  }
  // Both sides of the length, not just the short one. A short message runs off the end
  // of the array and traps whatever the guard does; a long one has its tail ignored, so
  // encapsulating under a 33-byte "message" would silently mean its first 32 bytes.
  for (const n of [0, 31, 33, 64]) {
    if (!traps(() => encaps(ek, new Uint8Array(n)))) throw new Error(`accepted a ${n}-byte message`);
  }
  for (const n of [0, DK_LEN - 1, DK_LEN + 1]) {
    if (!traps(() => decaps(new Uint8Array(n), new Uint8Array(CT_LEN)))) {
      throw new Error(`accepted a ${n}-byte decapsulation key`);
    }
  }
  for (const n of [0, CT_LEN - 1, CT_LEN + 1]) {
    if (!traps(() => decaps(dk, new Uint8Array(n)))) throw new Error(`accepted a ${n}-byte ciphertext`);
  }
});
Deno.test("mlkem: rejects an encapsulation key whose coefficients are out of range", () => {
  // FIPS 203 §7.2 requires the modulus check: every twelve-bit coefficient must be below
  // q. The test is that re-encoding what was decoded gives back the original bytes, which
  // fails exactly when some coefficient was 3329 or more. Skipping it lets a peer choose
  // arithmetic outside the ring.
  const seed = Uint8Array.from({ length: 64 }, (_, i) => i);
  const ek = Uint8Array.from(keyGen(seed).subarray(0, EK_LEN));
  const m = new Uint8Array(32);
  encaps(ek, m);   // the genuine key is accepted

  // 0xFFF is 4095, comfortably above q, in the first coefficient's twelve bits.
  const bad = Uint8Array.from(ek);
  bad[0] = 0xFF;
  bad[1] = bad[1] | 0x0F;
  if (!traps(() => encaps(bad, m))) throw new Error("accepted a coefficient at or above q");
});
