// The BLS12-381 base field, against Python's arbitrary-precision integers.
//
// The oracle is deliberately *not* this implementation. `test/vectors.json` is generated by
// `test/vectors.py` using Python's own big integers and nothing else, so every expected value
// comes from a second implementation of modular arithmetic that shares no code, no
// representation and no author's misreading with the one under test. Montgomery form is the
// exact kind of thing that passes every self-consistency check while being wrong — `a·1 == a`
// and `a + 0 == a` hold for a completely broken reduction — so a self-relation would prove
// almost nothing here.
//
// Regenerate with:  python3 packages/bls/test/vectors.py > packages/bls/test/vectors.json

import { wacBind } from "../../../harness/wacBind.ts";

const mod = await wacBind("packages/bls/test/wac/probe.wac") as unknown as {
  blsFpStatus(a: Uint8Array, b: Uint8Array): number;
  blsFpAdd(a: Uint8Array, b: Uint8Array): Uint8Array;
  blsFpSub(a: Uint8Array, b: Uint8Array): Uint8Array;
  blsFpMul(a: Uint8Array, b: Uint8Array): Uint8Array;
  blsFpNeg(a: Uint8Array): Uint8Array;
  blsFpSquare(a: Uint8Array): Uint8Array;
  blsFpOneBytes(): Uint8Array;
  blsFpRoundTrip(a: Uint8Array): Uint8Array;
  blsFpMulByOneIsIdentity(a: Uint8Array): boolean;
  blsFpIsZeroBytes(a: Uint8Array): boolean;
};

type Vectors = {
  p: string;
  one: string;
  cases: { a: string; b: string; add: string; sub: string; mul: string }[];
  unary: { a: string; neg: string; sq: string }[];
  bad: string[];
};
const v: Vectors = JSON.parse(
  await Deno.readTextFile(new URL("vectors.json", import.meta.url)),
);

const bytes = (hex: string) =>
  Uint8Array.from(hex.match(/../g)!.map((h) => parseInt(h, 16)));
const hex = (b: Uint8Array) => Array.from(b).map((x) => x.toString(16).padStart(2, "0")).join("");

Deno.test("addition, subtraction and multiplication agree with Python", () => {
  for (const c of v.cases) {
    const a = bytes(c.a), b = bytes(c.b);
    for (const [name, got, want] of [
      ["add", mod.blsFpAdd(a, b), c.add],
      ["sub", mod.blsFpSub(a, b), c.sub],
      ["mul", mod.blsFpMul(a, b), c.mul],
    ] as [string, Uint8Array, string][]) {
      if (hex(got) !== want) {
        throw new Error(`${name}(${c.a.slice(0, 12)}…, ${c.b.slice(0, 12)}…)\n` +
          `  got  ${hex(got)}\n  want ${want}`);
      }
    }
  }
});

Deno.test("negation and squaring agree with Python", () => {
  for (const u of v.unary) {
    const a = bytes(u.a);
    if (hex(mod.blsFpNeg(a)) !== u.neg) {
      throw new Error(`neg(${u.a.slice(0, 12)}…): got ${hex(mod.blsFpNeg(a))}, want ${u.neg}`);
    }
    if (hex(mod.blsFpSquare(a)) !== u.sq) {
      throw new Error(`sq(${u.a.slice(0, 12)}…): got ${hex(mod.blsFpSquare(a))}, want ${u.sq}`);
    }
  }
});

Deno.test("Montgomery form does not leak: one is one and every value round-trips", () => {
  // If `fromBytes` and `toBytes` were not exact inverses, most arithmetic would still look
  // self-consistent — this is the check that the form stays inside the field code.
  if (hex(mod.blsFpOneBytes()) !== v.one) {
    throw new Error(`one encodes as ${hex(mod.blsFpOneBytes())}, want ${v.one}`);
  }
  for (const u of v.unary) {
    if (hex(mod.blsFpRoundTrip(bytes(u.a))) !== u.a) {
      throw new Error(`round trip changed ${u.a}`);
    }
    if (!mod.blsFpMulByOneIsIdentity(bytes(u.a))) {
      throw new Error(`a·1 != a for ${u.a}`);
    }
  }
  if (!mod.blsFpIsZeroBytes(bytes(v.unary[0].a))) throw new Error("zero did not read as zero");
});

Deno.test("a value at or above p is refused, not reduced", () => {
  // Accepting a non-canonical encoding means two byte strings for one field element, which is
  // where signature malleability comes from. Every one of these is a valid 48-byte string and
  // an invalid field element.
  for (const b of v.bad) {
    const status = mod.blsFpStatus(bytes(b), bytes(v.one));
    if (status !== 1) throw new Error(`${b} was accepted (status ${status})`);
  }
  // And a short or long input is refused rather than padded.
  if (mod.blsFpStatus(new Uint8Array(47), new Uint8Array(48)) !== 1) {
    throw new Error("a 47-byte value was accepted");
  }
});
