// The BLS12-381 base field, against Python's arbitrary-precision integers.
//
// The oracle is deliberately *not* this implementation. `test/vectors.json` is generated by
// `test/vectors.py` using Python's own big integers and nothing else, so every expected value
// comes from a second implementation of modular arithmetic that shares no code, no
// representation and no author's misreading with the one under test. Montgomery form is the
// exact kind of thing that passes every self-consistency check while being wrong — `a·1 == a`
// and `a + 0 == a` hold for a completely broken reduction — so a self-relation would prove
// almost nothing here.
//
// Regenerate with:  python3 packages/bls/test/vectors.py > packages/bls/test/vectors.json

import { wacBind } from "../../../harness/wacBind.ts";

const mod = await wacBind("packages/bls/test/wac/probe.wac") as unknown as {
  blsModulusConstantsAgree(): boolean;
  blsFpStatus(a: Uint8Array, b: Uint8Array): number;
  blsFpAdd(a: Uint8Array, b: Uint8Array): Uint8Array;
  blsFpSub(a: Uint8Array, b: Uint8Array): Uint8Array;
  blsFpMul(a: Uint8Array, b: Uint8Array): Uint8Array;
  blsFpNeg(a: Uint8Array): Uint8Array;
  blsFpSquare(a: Uint8Array): Uint8Array;
  blsFpOneBytes(): Uint8Array;
  blsFpRoundTrip(a: Uint8Array): Uint8Array;
  blsFpMulByOneIsIdentity(a: Uint8Array): boolean;
  blsFpIsZeroBytes(a: Uint8Array): boolean;
};

type Vectors = {
  p: string;
  one: string;
  cases: { a: string; b: string; add: string; sub: string; mul: string }[];
  unary: { a: string; neg: string; sq: string }[];
  bad: string[];
};
const v: Vectors = JSON.parse(
  await Deno.readTextFile(new URL("vectors.json", import.meta.url)),
);

const bytes = (hex: string) =>
  Uint8Array.from(hex.match(/../g)!.map((h) => parseInt(h, 16)));
const hex = (b: Uint8Array) => Array.from(b).map((x) => x.toString(16).padStart(2, "0")).join("");

Deno.test("addition, subtraction and multiplication agree with Python", () => {
  for (const c of v.cases) {
    const a = bytes(c.a), b = bytes(c.b);
    for (const [name, got, want] of [
      ["add", mod.blsFpAdd(a, b), c.add],
      ["sub", mod.blsFpSub(a, b), c.sub],
      ["mul", mod.blsFpMul(a, b), c.mul],
    ] as [string, Uint8Array, string][]) {
      if (hex(got) !== want) {
        throw new Error(`${name}(${c.a.slice(0, 12)}…, ${c.b.slice(0, 12)}…)\n` +
          `  got  ${hex(got)}\n  want ${want}`);
      }
    }
  }
});

Deno.test("negation and squaring agree with Python", () => {
  for (const u of v.unary) {
    const a = bytes(u.a);
    if (hex(mod.blsFpNeg(a)) !== u.neg) {
      throw new Error(`neg(${u.a.slice(0, 12)}…): got ${hex(mod.blsFpNeg(a))}, want ${u.neg}`);
    }
    if (hex(mod.blsFpSquare(a)) !== u.sq) {
      throw new Error(`sq(${u.a.slice(0, 12)}…): got ${hex(mod.blsFpSquare(a))}, want ${u.sq}`);
    }
  }
});

Deno.test("Montgomery form does not leak: one is one and every value round-trips", () => {
  // If `fromBytes` and `toBytes` were not exact inverses, most arithmetic would still look
  // self-consistent — this is the check that the form stays inside the field code.
  if (hex(mod.blsFpOneBytes()) !== v.one) {
    throw new Error(`one encodes as ${hex(mod.blsFpOneBytes())}, want ${v.one}`);
  }
  for (const u of v.unary) {
    if (hex(mod.blsFpRoundTrip(bytes(u.a))) !== u.a) {
      throw new Error(`round trip changed ${u.a}`);
    }
    if (!mod.blsFpMulByOneIsIdentity(bytes(u.a))) {
      throw new Error(`a·1 != a for ${u.a}`);
    }
  }
  if (!mod.blsFpIsZeroBytes(bytes(v.unary[0].a))) throw new Error("zero did not read as zero");
});

Deno.test("a value at or above p is refused, not reduced", () => {
  // Accepting a non-canonical encoding means two byte strings for one field element, which is
  // where signature malleability comes from. Every one of these is a valid 48-byte string and
  // an invalid field element.
  for (const b of v.bad) {
    const status = mod.blsFpStatus(bytes(b), bytes(v.one));
    if (status !== 1) throw new Error(`${b} was accepted (status ${status})`);
  }
  // And a short or long input is refused rather than padded.
  if (mod.blsFpStatus(new Uint8Array(47), new Uint8Array(48)) !== 1) {
    throw new Error("a 47-byte value was accepted");
  }
});

// ── Inversion, roots, and Fp2 ─────────────────────────────────────────────────

const mod2 = mod as unknown as {
  blsFpInvert(a: Uint8Array): Uint8Array;
  blsFpSqrt(a: Uint8Array): Uint8Array;
  blsFpLarger(a: Uint8Array): boolean;
  blsFp2Op(ac0: Uint8Array, ac1: Uint8Array, bc0: Uint8Array, bc1: Uint8Array, op: number): Uint8Array;
  blsFp2Norm(ac0: Uint8Array, ac1: Uint8Array): Uint8Array;
  blsFp2OneIsIdempotent(): boolean;
};
type More = {
  inv: { a: string; inv: string }[];
  roots: { a: string; sqrt: string | null }[];
  fp2: Record<string, { c0: string; c1: string } | string>[];
};
const w = v as unknown as Vectors & More;

Deno.test("inversion agrees with Python, and zero has none", () => {
  for (const c of w.inv) {
    const got = hex(mod2.blsFpInvert(bytes(c.a)));
    if (got !== c.inv) throw new Error(`inv(${c.a.slice(0, 12)}…)\n  got  ${got}\n  want ${c.inv}`);
  }
  if (mod2.blsFpInvert(bytes(v.unary[0].a)).length !== 0) {
    throw new Error("zero was inverted");
  }
});

Deno.test("square roots are found where they exist and refused where they do not", () => {
  // Sixteen of thirty-three of these are squares. A routine that returned its exponentiation
  // without checking would pass on those sixteen and hand a non-root back for the rest — and
  // point decompression is fed attacker-controlled bytes, so that is a point off the curve
  // going into a pairing.
  let squares = 0;
  for (const r of w.roots) {
    const got = mod2.blsFpSqrt(bytes(r.a));
    if (r.sqrt === null) {
      if (got.length !== 0) throw new Error(`sqrt(${r.a.slice(0, 12)}…) returned a non-root`);
    } else {
      squares++;
      // Either root is correct; the vector holds a^((p+1)/4), and the other is p − that.
      const h = hex(got);
      if (h !== r.sqrt) {
        const neg = ((BigInt("0x" + w.p) - BigInt("0x" + h)) % BigInt("0x" + w.p))
          .toString(16).padStart(96, "0");
        if (neg !== r.sqrt) {
          throw new Error(`sqrt(${r.a.slice(0, 12)}…)\n  got  ${h}\n  want ${r.sqrt} (or its negation)`);
        }
      }
    }
  }
  if (squares === 0) throw new Error("no squares in the corpus — the vectors are wrong");
});

Deno.test("Fp2 arithmetic agrees with Python", () => {
  const ops: [string, number][] = [
    ["add", 0], ["sub", 1], ["mul", 2], ["sq", 3], ["conj", 4], ["mulByU", 5], ["mulByXi", 6],
  ];
  for (const c of w.fp2) {
    const a = c.a as { c0: string; c1: string };
    const b = c.b as { c0: string; c1: string };
    for (const [name, op] of ops) {
      const want = c[name] as { c0: string; c1: string };
      const got = mod2.blsFp2Op(bytes(a.c0), bytes(a.c1), bytes(b.c0), bytes(b.c1), op);
      const gotC0 = hex(got.subarray(0, 48));
      const gotC1 = hex(got.subarray(48));
      if (gotC0 !== want.c0 || gotC1 !== want.c1) {
        throw new Error(`fp2 ${name}\n  got  c0=${gotC0} c1=${gotC1}\n  want c0=${want.c0} c1=${want.c1}`);
      }
    }
    const norm = hex(mod2.blsFp2Norm(bytes(a.c0), bytes(a.c1)));
    if (norm !== c.norm as string) {
      throw new Error(`fp2 norm\n  got  ${norm}\n  want ${c.norm}`);
    }
  }
  if (!mod2.blsFp2OneIsIdempotent()) throw new Error("1·1 != 1 in Fp2");
});

// ── The tower ─────────────────────────────────────────────────────────────────

const modT = mod as unknown as {
  blsFp6Op(a: Uint8Array, b: Uint8Array, op: number): Uint8Array;
  blsFp12Op(a: Uint8Array, b: Uint8Array, op: number): Uint8Array;
  blsFp12InverseIsInverse(a: Uint8Array): boolean;
};
type Tower = { fp6: Record<string, string[]>[]; fp12: Record<string, string[]>[] };
const t = v as unknown as Vectors & Tower;

const flat = (coeffs: string[]) => {
  const out = new Uint8Array(coeffs.length * 48);
  coeffs.forEach((c, i) => out.set(bytes(c), i * 48));
  return out;
};
const unflat = (b: Uint8Array) => {
  const out: string[] = [];
  for (let i = 0; i < b.length; i += 48) out.push(hex(b.subarray(i, i + 48)));
  return out;
};

const OPS: [string, number][] = [
  ["mul", 0], ["sq", 1], ["mulByV", 2], ["inv", 3], ["frob1", 4], ["frob2", 5], ["frob3", 6],
];

Deno.test("Fp6 arithmetic and Frobenius agree with the Python tower", () => {
  for (const c of t.fp6) {
    for (const [name, op] of OPS) {
      const got = unflat(modT.blsFp6Op(flat(c.a), flat(c.b), op));
      if (got.join() !== c[name].join()) {
        throw new Error(`fp6 ${name}\n  got  ${got[0]}…\n  want ${c[name][0]}…`);
      }
    }
  }
});

Deno.test("Fp12 arithmetic and Frobenius agree with the Python tower", () => {
  // Frobenius is the one worth naming: `tower.py` validates its constants by comparing
  // Frobenius-by-constant against actually raising to the pⁿ-th power in the tower, so a wrong
  // digit in any of the nine twelve-word tables fails there before reaching here.
  const ops: [string, number][] = [
    ["mul", 0], ["sq", 1], ["conj", 2], ["inv", 3], ["frob1", 4], ["frob2", 5], ["frob3", 6],
  ];
  for (const c of t.fp12) {
    for (const [name, op] of ops) {
      const got = unflat(modT.blsFp12Op(flat(c.a), flat(c.b), op));
      if (got.join() !== c[name].join()) {
        throw new Error(`fp12 ${name}\n  got  ${got[0]}…\n  want ${c[name][0]}…`);
      }
    }
    if (!modT.blsFp12InverseIsInverse(flat(c.a))) {
      throw new Error("a · a⁻¹ != 1 in Fp12");
    }
  }
});

// p is spelled twice in `src/fp.wac` — as an array for `fpMul`, and as `P0..P11` constants for the
// reduction that every add and subtract goes through. Nothing else in the suite would notice them
// drifting apart, because both spellings are used together in almost every operation and a
// consistent pair of wrong values is still self-consistent. This ties them to each other.
Deno.test("the modulus constants and the modulus array are the same p", () => {
  if (!mod.blsModulusConstantsAgree()) {
    throw new Error("P0..P11 disagree with modulus() — the reduction is against the wrong p");
  }
});
